# What is PyTorch

It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs.
- A deep learning research platform that provides maximum flexibility and speed.

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

    Note: An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8361e+25, 1.4603e-19],
        [1.6795e+08, 4.7423e+30, 4.7393e+30],
        [9.5461e-01, 4.4377e+27, 1.7975e+19],
        [4.6894e+27, 7.9463e+08, 3.2604e-12]])

Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.6278, 0.7898, 0.0956],
        [0.0581, 0.5207, 0.4373],
        [0.8774, 0.6295, 0.8804],
        [0.1867, 0.4743, 0.0905],
        [0.4349, 0.6129, 0.6355]])

Construct a matrix filled zeros and of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-1.2733, -1.5038,  0.8104],
        [-1.0535,  0.7054,  1.9946],
        [ 0.0065, -0.1982, -1.6715],
        [-1.5152, -1.1523,  0.9475],
        [ 0.9828,  0.6115,  0.7405]])

Get its size:

In [8]:
x.size()

torch.Size([5, 3])

    torch.Size is in fact a tuple, so it supports all tuple operations.

### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.8744, -1.2291,  1.7610],
        [-0.6676,  1.1896,  2.1990],
        [ 0.4476,  0.5128, -0.6732],
        [-0.6828, -0.3511,  1.7783],
        [ 1.8367,  0.7782,  1.6327]])


Addition: syntax 2

In [10]:
torch.add(x, y)

tensor([[-0.8744, -1.2291,  1.7610],
        [-0.6676,  1.1896,  2.1990],
        [ 0.4476,  0.5128, -0.6732],
        [-0.6828, -0.3511,  1.7783],
        [ 1.8367,  0.7782,  1.6327]])

Addition: providing an output tensor as argument

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.8744, -1.2291,  1.7610],
        [-0.6676,  1.1896,  2.1990],
        [ 0.4476,  0.5128, -0.6732],
        [-0.6828, -0.3511,  1.7783],
        [ 1.8367,  0.7782,  1.6327]])


Addition: in-place

In [12]:
# add x to y
y.add_(x)
print(y)

tensor([[-0.8744, -1.2291,  1.7610],
        [-0.6676,  1.1896,  2.1990],
        [ 0.4476,  0.5128, -0.6732],
        [-0.6828, -0.3511,  1.7783],
        [ 1.8367,  0.7782,  1.6327]])


    Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [13]:
print(x[:, 1])

tensor([-1.5038,  0.7054, -0.1982, -1.1523,  0.6115])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`:

In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number:

In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.3370])
1.3369886875152588


Read later:

100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described here.

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

See how the numpy array changed in value.

In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically.

In [19]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.


## CUDA Tensors
Tensors can be moved onto any device using the `.to` method.

In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device('cuda') # a CUDA device object
    y = torch.ones_like(x, device=device) # directly create a tensor on GPU
    x = x.to(device) # or just use strings .to("cuda")
    z = x + y
    print(z)
    print(z.to('cpu', torch.double)) # .to can also change dtype together!